[tool.poetry]
name = "refnormal"
version = "0.1.0"
description = ""
authors = ["alex <aez2000@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
langchain = "^0.1.13"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
